name: Run Tests
on: [push, pull_request]
jobs:
  build:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Download source
        uses: actions/checkout@v2
      - name: Install Crystal
        uses: oprypin/install-crystal@v1
      - name: Install Crystal libs
        run: shards install
      - name: Install libs
        run: sudo ./rsrc/install_linux.sh
      - name: Run Tests
        run: crystal spec --tag gh-actions